### ISSUE TITLE
I'm proud of you for updating your software, you're great!

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#7] opened 2021-12-28 14:05 UTC
Replaced most of the while loops to for loops

Will it make the code execute faster?

Can we still have room for improvement for fishing cycles?

**Comment by nebelorz** [comment] 2021-12-28 14:54
Heya! Thanks for your words 😁

The loops cannot be faster I think, adding threads truly doesn't make a difference, as the program should check sequentally the steps so... 

The code doesn't execute faster with the last update, but now the reconnection should work all the times, as the for loops aren't infinite (though it should take some time to detect it, around 1~ minute). 

I think it's time to start a new project, the auto fisher does all the things supposed to do now 🙃

If there's any bug or cool feature to add just tell me and I'll take a look for sure! 

Thanks for all the feedback @fkue587, and thanks for the kind words dude!🙂

**Comment by fkue587** [comment] 2021-12-28 15:44
Many programmers make programs that are stable and basically won't be updated, but I didn't expect you to silently update the software, it seems that you are still working overtime after Christmas. I'm glad to see that you're still refining your skills, many times people can't stick to them, such as myself. Haha.


Please add the following features if you can! Of course this is not necessary, you can also not add!
1. 
Global shortcut keys - Start and Pause

or 

Start and Pause buttons



I wish you a happy life.

**Comment by nebelorz** [comment] 2021-12-28 23:18
I've been messing around with the program, implemented the hotkey feature and I was trying to give some color to the console outputs, but then I remembered you told me you couldn't use the "console.py" to launch the program right?

Can you tell me more about that? As if you launch it directly using the CMD, the colors doesn't show and it messes the outputs 😣 Also just double clicking console.py, the log always stays on top, so you don't need anything else to keep it on top😉


Using console.py:
![image](https://user-images.githubusercontent.com/65920053/147613703-a95c8fd5-db75-426b-b67c-023f697d7bdd.png)

Calling main.py directly from CMD
![image](https://user-images.githubusercontent.com/65920053/147613775-9bcb0fd3-a7a1-431e-a7c3-d1816197bf52.png)

If we find the issue, I can color the info and loop messages and that'll be the final version 🙃

**Comment by fkue587** [comment] 2021-12-29 13:54
![微信截图_20211229210442](https://user-images.githubusercontent.com/93835049/147669304-10bdb0c3-e7a4-4eec-b041-e03edb5e929e.png)
My program is linked.
Notepad++
so my .py program has changed.

**Comment by nebelorz** [comment] 2021-12-29 17:13
You should select to run the console.py file with Python directly, then it should work.

Anyways, I'm uploading the program with the hotkey feature, without the console colors though 🙄

**Comment by fkue587** [comment] 2021-12-30 00:37
![image](https://user-images.githubusercontent.com/93835049/147712803-4eed12d7-5820-4248-a280-d3d242670353.png)
This can happen if the network is bad.
This is a small problem. It's okay if you don't fix it.

**Comment by fkue587** [comment] 2021-12-30 00:45
I'm looking for a solution to the program association myself... See how to get Python running again... My .py program is associated with Notepad and opens as a text file. I'm looking for a way to fix .

**Comment by nebelorz** [comment] 2021-12-30 07:15
> ![image](https://user-images.githubusercontent.com/93835049/147712803-4eed12d7-5820-4248-a280-d3d242670353.png) This can happen if the network is bad. This is a small problem. It's okay if you don't fix it.

I can fix it today, that's simple 😛

If you're using windows, just right click a .py file and click properties, then there you can assign a default program to open those files.

**Comment by fkue587** [comment] 2021-12-30 07:15
Today I updated from 1.12 to 1.14, but the fishing is not smooth, fishing cycle, the perspective is slower than the casting speed. This led to failed casts and then re-baiting. Re-fishing. Affects speed.

**Comment by fkue587** [comment] 2021-12-30 07:16
Today I updated from 1.12 to 1.14, but the fishing is not smooth, fishing cycle, the perspective is slower than the casting speed. This led to failed casts and then re-baiting. Re-fishing. Affects speed.

**Comment by fkue587** [comment] 2021-12-30 07:17
I fixed the .py program, but when I double-click to open console.py, it does not show the details, but only opens the CMD window. The program works fine, and the global shortcuts work. It just doesn't show the fishing information window.

**Comment by nebelorz** [comment] 2021-12-30 07:22
> Today I updated from 1.12 to 1.14, but the fishing is not smooth, fishing cycle, the perspective is slower than the casting speed. This led to failed casts and then re-baiting. Re-fishing. Affects speed.

This shouldn't happen, as I didn't touch any of this after 1.1.2 let me test it today. 

The console.py should open CMD and execute the program via command line, so it's the same as opening CMD->python main.py, basically the same as the old bat file. I'll add some delay just in case.

**Comment by fkue587** [comment] 2021-12-30 07:33
1.12 tested again without problems. It is safe to assume that the problem is in 1.14.
It should replace most of the while loops with for loops.
The problem may be here .

**Comment by nebelorz** [comment] 2021-12-30 14:37
> Today I updated from 1.12 to 1.14, but the fishing is not smooth, fishing cycle, the perspective is slower than the casting speed. This led to failed casts and then re-baiting. Re-fishing. Affects speed.

I'm testing it right now and I've found what you mean, as the loop for checking certain things is too low if you fish on non-deep areas, and it breaks before anything's catched 😅 I've already fixed it. 

I'll re-work the reconnection to be looping from step 1, as it can lead to an infinite loop if you have bad connection.

**Comment by nebelorz** [comment] 2021-12-30 17:15
Check the [latest release](https://github.com/nebelorz/New-World-Auto-Fishing/releases/tag/v1.1.5) @fkue587!

Now should work perfectly as the previous versions, but with added reconnection (no longer in beta?) and hotkey features.
Tell me if there's any issue with those! 🙃

By the way, try to run console.py from just double clicking it and tell me if it works for you now please!

Thanks!😁

**Comment by fkue587** [comment] 2021-12-30 17:25
useing 1.15  test

**Comment by fkue587** [comment] 2021-12-30 17:39
![微信图片编辑_20211231013155](https://user-images.githubusercontent.com/93835049/147774890-bb581c72-1d3b-45c8-bf95-ccd0514edd44.png)
Double click console.py

**Comment by fkue587** [comment] 2021-12-30 17:42
1.15 should add some delay in .
![1111111111](https://user-images.githubusercontent.com/93835049/147804681-aab0f16b-0341-4849-b4d1-8a7dd57b07a8.jpg)

Loop error.

**Comment by nebelorz** [comment] 2021-12-31 00:05
[Hotfixed](https://github.com/nebelorz/New-World-Auto-Fishing/releases/tag/v1.1.51) the skip animation, as if you got mastery levels (fishing skill 200+) it got messed up, now works perfectly.

I cannot see your last image, can you re-upload it again please?

**Comment by fkue587** [comment] 2021-12-31 05:16
1.1.51 The problem is still the same I have updated the picture in the message above.

**Comment by fkue587** [comment] 2021-12-31 05:18
1.1.51 The mouse will be clicked once after the end of the loop, resulting in a cast.
The cycle starts again.

**Comment by fkue587** [comment] 2021-12-31 05:33
It is still 1.12 without problems.
There are problems with subsequent versions.
1.1.51 still has problems. I will continue to test 1.1.51 to see if there are more problems.

**Comment by nebelorz** [comment] 2021-12-31 08:48
Gotcha! will give it a look!

**Comment by nebelorz** [comment] 2021-12-31 13:51
Test this build, I've optimized the reel function (it reels more efficiently now) and the re-cast issue shouldn't be a problem.

I am testing it too, will upload it as a final release if everything works as intended 😁

[New-World-Auto-Fishing v1.1.52(test).zip](https://github.com/nebelorz/New-World-Auto-Fishing/files/7796332/New-World-Auto-Fishing.v1.1.52.test.zip)

**Comment by nebelorz** [comment] 2021-12-31 15:09
All the issues are fixed in this build, could you test it out @fkue587? everything works fine now.
I re-worked some of the reel loop, it should work smoother and a little bit faster than before.

[New-World-Auto-Fishing v1.1.6.zip](https://github.com/nebelorz/New-World-Auto-Fishing/files/7796479/New-World-Auto-Fishing.v1.1.6.zip)

If you don't find any other issues, I'll upload it as a release 😁

**Comment by fkue587** [comment] 2021-12-31 16:55
This time the cycle is much faster. Faster recognition and smarter puller! Perfectly! Happy New Year! This is my New Year's gift! Thank you very much Santa!

**Comment by nebelorz** [comment] 2021-12-31 17:01
> This time the cycle is much faster. Faster recognition and smarter puller! Perfectly! Happy New Year! This is my New Year's gift! Thank you very much Santa!

Thanks you for testing all the builds man!
If there's any other issue, just open a new one and I'll take a look on it as always (:

Happy new year @fkue587 🎉!

**Closed as completed by nebelorz** 2021-12-31 17:01 UTC
Labels: bug, enhancement
